# Numpy Practice 
## Arrays 

In [1]:
import array

In [3]:
L = list(range(10))

In [4]:
A = array.array('i',L)

In [5]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
import numpy as np
([x for x in dir(np)])

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [8]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

 Creating Arrays from Scratch 

In [9]:
np.zeros(10, dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Creating a 3x5 array filled with 3.14

In [10]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Getting the details of the method or function in an attribute .eg:
help(getattr(np, 'array'))

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
import numpy as np
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
np.random.randint(5)

4

In [2]:
import random
import numpy as np
np.random.randint(10, size=6)

array([9, 7, 9, 7, 8, 6], dtype=int32)

In [3]:
np.random.seed(0)

In [13]:
x1 = np.ones((2,2,2,2), dtype='int8')
print(x1.ndim)
print(x1.size)
print(x1.itemsize)
print(x1.shape)
print(x1.nbytes)
print(x1)

4
16
1
(2, 2, 2, 2)
16
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


In [1]:
import numpy as np
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
my_array[1::3]

array([1, 4, 7])

# Reshaping of arrays 

In [3]:
import numpy as np
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3) 

[1 2 3] [99 99] [3 2 1]
